spring:
  profiles:
    active: local
server:
  port: 8081
---
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: "movie-genre"
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "Group_id1"
      properties:
        retry-backoff-ms: 1000
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
